import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { BoundingBox } from "@invoice/contracts";
import type { InvoiceLayout, RecordedBox, RenderResult, TextToken } from "./types.js";

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 54;
const RIGHT_EDGE = PAGE_WIDTH - MARGIN;

const INK = rgb(0.1, 0.12, 0.16);
const MUTED = rgb(0.42, 0.45, 0.5);
const RULE = rgb(0.8, 0.82, 0.85);

interface Ctx {
  page: import("pdf-lib").PDFPage;
  regular: import("pdf-lib").PDFFont;
  bold: import("pdf-lib").PDFFont;
  boxes: Record<string, RecordedBox>;
}

function normalizedBox(xLeft: number, yTop: number, width: number, size: number): BoundingBox {
  // Pad the recorded region slightly so highlights read as a comfortable box.
  const padX = 3;
  const padY = 3;
  const height = size * 1.25;
  return {
    x: Math.max(0, (xLeft - padX) / PAGE_WIDTH),
    y: Math.max(0, (yTop - padY) / PAGE_HEIGHT),
    width: Math.min(1, (width + padX * 2) / PAGE_WIDTH),
    height: Math.min(1, (height + padY * 2) / PAGE_HEIGHT),
  };
}

interface DrawOpts {
  size?: number;
  bold?: boolean;
  color?: import("pdf-lib").RGB;
  align?: "left" | "right";
  rightEdge?: number;
}

/** Draws text and returns the top-based normalized box it occupies. */
function draw(ctx: Ctx, text: string, xLeft: number, yTop: number, opts: DrawOpts = {}): BoundingBox {
  const size = opts.size ?? 10;
  const font = opts.bold ? ctx.bold : ctx.regular;
  const width = font.widthOfTextAtSize(text, size);
  const x = opts.align === "right" ? (opts.rightEdge ?? RIGHT_EDGE) - width : xLeft;
  // pdf-lib origin is bottom-left; baseline sits `size` below the visual top.
  const baseline = PAGE_HEIGHT - yTop - size;
  ctx.page.drawText(text, {
    x,
    y: baseline,
    size,
    font,
    color: opts.color ?? INK,
  });
  return normalizedBox(x, yTop, width, size);
}

function record(ctx: Ctx, token: TextToken, box: BoundingBox): void {
  if (token.sourcePath) {
    ctx.boxes[token.sourcePath] = { page: 1, box, text: token.text };
  }
}

/**
 * Renders an invoice layout to a deterministic single-page PDF and records the
 * normalized bounding box of every tagged token for provenance highlighting.
 */
export async function renderInvoice(layout: InvoiceLayout): Promise<RenderResult> {
  const pdf = await PDFDocument.create();
  // Fixed metadata so generated bytes (and their sha256) are deterministic.
  const epoch = new Date(0);
  pdf.setCreationDate(epoch);
  pdf.setModificationDate(epoch);
  pdf.setProducer("distil-fixtures");
  pdf.setTitle(layout.documentTitle);

  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const ctx: Ctx = { page, regular, bold, boxes: {} };

  // Header: vendor name (left) and document title (right).
  const vendorBox = draw(ctx, layout.vendorName.text, MARGIN, 54, { size: 20, bold: true });
  record(ctx, layout.vendorName, vendorBox);

  let y = 80;
  for (const line of layout.vendorAddress) {
    draw(ctx, line, MARGIN, y, { size: 9, color: MUTED });
    y += 13;
  }

  draw(ctx, layout.documentTitle, 0, 50, {
    size: 26,
    bold: true,
    align: "right",
    color: rgb(0.2, 0.35, 0.7),
  });

  // Meta block (right side).
  let metaY = 96;
  for (const row of layout.meta) {
    draw(ctx, row.label, 360, metaY, { size: 9, color: MUTED, align: "left" });
    const valueBox = draw(ctx, row.value.text, 0, metaY, { size: 10, bold: true, align: "right" });
    record(ctx, row.value, valueBox);
    metaY += 18;
  }

  // Bill-to block (left, below address).
  if (layout.billTo && layout.billTo.length > 0) {
    let billY = Math.max(y + 12, 150);
    draw(ctx, "BILL TO", MARGIN, billY, { size: 8, bold: true, color: MUTED });
    billY += 14;
    for (const line of layout.billTo) {
      draw(ctx, line, MARGIN, billY, { size: 9 });
      billY += 12;
    }
  }

  // Line-items table.
  const tableTop = 250;
  const colDesc = MARGIN;
  const colQtyRight = 380;
  const colUnitRight = 470;
  const colTotalRight = RIGHT_EDGE;

  draw(ctx, layout.lineItemHeaders.description, colDesc, tableTop, { size: 8, bold: true, color: MUTED });
  draw(ctx, layout.lineItemHeaders.qty, 0, tableTop, { size: 8, bold: true, color: MUTED, align: "right", rightEdge: colQtyRight });
  draw(ctx, layout.lineItemHeaders.unitPrice, 0, tableTop, { size: 8, bold: true, color: MUTED, align: "right", rightEdge: colUnitRight });
  draw(ctx, layout.lineItemHeaders.lineTotal, 0, tableTop, { size: 8, bold: true, color: MUTED, align: "right", rightEdge: colTotalRight });

  page.drawLine({
    start: { x: MARGIN, y: PAGE_HEIGHT - tableTop - 12 },
    end: { x: RIGHT_EDGE, y: PAGE_HEIGHT - tableTop - 12 },
    thickness: 0.75,
    color: RULE,
  });

  let rowY = tableTop + 20;
  for (const item of layout.lineItems) {
    const descBox = draw(ctx, item.description.text, colDesc, rowY, { size: 9 });
    record(ctx, item.description, descBox);
    const qtyBox = draw(ctx, item.qty.text, 0, rowY, { size: 9, align: "right", rightEdge: colQtyRight });
    record(ctx, item.qty, qtyBox);
    const unitBox = draw(ctx, item.unitPrice.text, 0, rowY, { size: 9, align: "right", rightEdge: colUnitRight });
    record(ctx, item.unitPrice, unitBox);
    const totalBox = draw(ctx, item.lineTotal.text, 0, rowY, { size: 9, align: "right", rightEdge: colTotalRight });
    record(ctx, item.lineTotal, totalBox);
    rowY += 17;
  }

  // Amounts block (right side, below the table).
  let amountY = rowY + 18;
  page.drawLine({
    start: { x: 360, y: PAGE_HEIGHT - amountY + 6 },
    end: { x: RIGHT_EDGE, y: PAGE_HEIGHT - amountY + 6 },
    thickness: 0.75,
    color: RULE,
  });
  for (const row of layout.amounts) {
    draw(ctx, row.label, 360, amountY, {
      size: row.emphasize ? 11 : 10,
      bold: row.emphasize,
      color: row.emphasize ? INK : MUTED,
    });
    const valueBox = draw(ctx, row.value.text, 0, amountY, {
      size: row.emphasize ? 12 : 10,
      bold: row.emphasize,
      align: "right",
    });
    record(ctx, row.value, valueBox);
    amountY += 20;
  }

  // Footer notes.
  if (layout.notes && layout.notes.length > 0) {
    let noteY = Math.max(amountY + 30, 700);
    for (const line of layout.notes) {
      draw(ctx, line, MARGIN, noteY, { size: 8, color: MUTED });
      noteY += 12;
    }
  }

  const pdfBytes = await pdf.save();
  return {
    pdfBytes,
    pages: [{ page: 1, widthPt: PAGE_WIDTH, heightPt: PAGE_HEIGHT }],
    boxes: ctx.boxes,
  };
}
